In [1]:
import numpy as np
import pickle
import pandas as pd
from preprocess1 import *  # this is for loading the .py file which contains all the libraries and the custom functions.
from imblearn.over_sampling import SMOTE

In [2]:
df=pd.read_csv('titanic.csv')

In [3]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,892,0,3,"Kelly, Mr. James",male,34.5,0,0,330911,7.8292,NaN,Q
1,893,1,3,"Wilkes, Mrs. James (Ellen Needs)",female,47.0,1,0,363272,7.0000,NaN,S
2,894,0,2,"Myles, Mr. Thomas Francis",male,62.0,0,0,240276,9.6875,NaN,Q
3,895,0,3,"Wirz, Mr. Albert",male,27.0,0,0,315154,8.6625,NaN,S
4,896,1,3,"Hirvonen, Mrs. Alexander (Helga E Lindqvist)",female,22.0,1,1,3101298,12.2875,NaN,S

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 418 entries, 0 to 417
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  418 non-null    int64
 1   Survived     418 non-null    int64
 2   Pclass       418 non-null    int64
 3   Name         418 non-null    object
 4   Sex          418 non-null    object
 5   Age          332 non-null    float64
 6   SibSp        418 non-null    int64
 7   Parch        418 non-null    int64
 8   Ticket       418 non-null    object
 9   Fare         417 non-null    float64
 10  Cabin        91 non-null     object
 11  Embarked     418 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 39.3+ KB

#  Load the pickle file :

In [5]:
file=open("titanic.pkl","rb")

In [6]:
pre = pickle.load(file)

# Load the preprocessor :

In [7]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,892,0,3,"Kelly, Mr. James",male,34.5,0,0,330911,7.8292,NaN,Q
1,893,1,3,"Wilkes, Mrs. James (Ellen Needs)",female,47.0,1,0,363272,7.0000,NaN,S
2,894,0,2,"Myles, Mr. Thomas Francis",male,62.0,0,0,240276,9.6875,NaN,Q
3,895,0,3,"Wirz, Mr. Albert",male,27.0,0,0,315154,8.6625,NaN,S
4,896,1,3,"Hirvonen, Mrs. Alexander (Helga E Lindqvist)",female,22.0,1,1,3101298,12.2875,NaN,S

In [ ]:
file

## This is the preprocessor that was defined in the previous file.

- You can load the preprocessor pipeline  anywhere using the above code for further processsing and for model evaluation.

### What are the further processing steps:

- You need to further check for the null values.
- Correlation between the target columns and the other columns.
- Check for outliers too and if having remove them.
- Scaling the data if needed.
- use transformation if the columns were skewed in distribution.
- splitting the data in train and test.
- Model Creation.
- Model evaluation.
- Hyperparameter Tune the model for the better results.

# Imputing null values :

In [8]:
df=df.drop(['Ticket','PassengerId','Name','Cabin'], axis=1)

In [9]:
df.isnull().sum()

Survived     0
Pclass       0
Sex          0
Age         86
SibSp        0
Parch        0
Fare         1
Embarked     0
dtype: int64

In [10]:
df.loc[df['Age'].isnull(),'Age']=df['Age'].median()

In [11]:
df.loc[df['Fare'].isnull(),'Fare']=50

In [12]:
df.isnull().sum()

Survived    0
Pclass      0
Sex         0
Age         0
SibSp       0
Parch       0
Fare        0
Embarked    0
dtype: int64

# Transforming the data :

In [13]:
df.head()

   Survived  Pclass     Sex   Age  SibSp  Parch     Fare Embarked
0         0       3    male  34.5      0      0   7.8292        Q
1         1       3  female  47.0      1      0   7.0000        S
2         0       2    male  62.0      0      0   9.6875        Q
3         0       3    male  27.0      0      0   8.6625        S
4         1       3  female  22.0      1      1  12.2875        S

In [14]:
processed_data=pre.fit_transform(df)

C:\ProgramData\anaconda3\Lib\site-packages\sklearn\preprocessing\_label.py:114: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

In [17]:
processed_data.shape

(418, 9)

In [22]:
df.columns[1:]

Index(['Pclass', 'Sex', 'Age', 'SibSp', 'Parch', 'Fare', 'Embarked'], dtype='object')

In [23]:
pd.DataFrame(processed_data)

       0    1         2      3    4    5    6    7    8
0    0.0  1.0 -0.498984  0.345  1.0  3.0  0.0  0.0  0.0
1    1.0  0.0 -0.513850  0.470  2.0  3.0  1.0  0.0  1.0
2    0.0  1.0 -0.465668  0.620  1.0  2.0  0.0  0.0  0.0
3    0.0  1.0 -0.484044  0.270  2.0  3.0  0.0  0.0  0.0
4    1.0  0.0 -0.419055  0.220  2.0  3.0  1.0  1.0  1.0
..   ...  ...       ...    ...  ...  ...  ...  ...  ...
413  0.0  1.0 -0.495025  0.270  2.0  3.0  0.0  0.0  0.0
414  1.0  0.0  1.313032  0.390  0.0  1.0  0.0  0.0  1.0
415  0.0  1.0 -0.509368  0.385  2.0  3.0  0.0  0.0  0.0
416  0.0  1.0 -0.495025  0.270  2.0  3.0  0.0  0.0  0.0
417  0.0  1.0 -0.238504  0.270  0.0  3.0  1.0  1.0  0.0

[418 rows x 9 columns]

## Now the dataset is preprocessed and can be used by a model.

                                          ** HAPPY LEARNING **